FROM python:3.10-slim

WORKDIR /app

COPY ./app/app_api.py .
COPY ./models ./models
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["uvicorn", "app_api:app", "--host", "0.0.0.0", "--port", "5000"]

